
package com.javajee.ws.wsimportex.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "EmployeeService", targetNamespace = "http://wsimportex.ws.javajee.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeeService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.javajee.ws.wsimportex.Employee>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findEmployees", targetNamespace = "http://wsimportex.ws.javajee.com/", className = "com.javajee.ws.wsimportex.client.FindEmployees")
    @ResponseWrapper(localName = "findEmployeesResponse", targetNamespace = "http://wsimportex.ws.javajee.com/", className = "com.javajee.ws.wsimportex.client.FindEmployeesResponse")
    public List<Employee> findEmployees(
        @WebParam(name = "arg0", targetNamespace = "")
        List<Integer> arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.javajee.ws.wsimportex.Employee
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findEmployee", targetNamespace = "http://wsimportex.ws.javajee.com/", className = "com.javajee.ws.wsimportex.client.FindEmployee")
    @ResponseWrapper(localName = "findEmployeeResponse", targetNamespace = "http://wsimportex.ws.javajee.com/", className = "com.javajee.ws.wsimportex.client.FindEmployeeResponse")
    public Employee findEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.javajee.ws.wsimportex.Employee>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAllEmployees", targetNamespace = "http://wsimportex.ws.javajee.com/", className = "com.javajee.ws.wsimportex.client.FindAllEmployees")
    @ResponseWrapper(localName = "findAllEmployeesResponse", targetNamespace = "http://wsimportex.ws.javajee.com/", className = "com.javajee.ws.wsimportex.client.FindAllEmployeesResponse")
    public List<Employee> findAllEmployees();

}
